#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Jul 23, 2020 02:28:26 PM CST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background #b1bccd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1368x830
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1924 1030
    wm minsize $top 152 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $top.m45 add cascade \
        -menu "$top.m45.men46" -label 文件 
    set site_3_0 $top.m45
    menu $site_3_0.men46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0.men46 add command \
        -command {#} -label {新建        } 
    $site_3_0.men46 add command \
        -command {#open_file} -label 打开 
    $top.m45 add cascade \
        -menu "$top.m45.men47" -label 处理 
    set site_3_0 $top.m45
    menu $site_3_0.men47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0.men47 add command \
        -command {#auto_processing } -label {自动测量       } 
    $site_3_0.men47 add command \
        -command {#bundle_adjustment} -label 光束法平差 
    $site_3_0.men47 add command \
        -command {#} -label 平差结果 
    $site_3_0.men47 add command \
        -command {#scan_setting} -label 扫描设置 
    $site_3_0.men47 add command \
        -command {#match_setting} -label 匹配设置 
    $site_3_0.men47 add command \
        -command {#bundle_adjustment_setting} -label 平差设置 
    canvas $top.can49 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 649 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 1064 
    vTcl:DefineAlias "$top.can49" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr50 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr50" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $top.scr50.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu51 \
        -command import_imgs -takefocus {} -text 导入图像 -cursor hand2 
    vTcl:DefineAlias "$top.tBu51" "import_imgs" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu52 \
        -command import_camera -takefocus {} -text 导入相机文件 -cursor hand2 
    vTcl:DefineAlias "$top.tBu52" "import_camera" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu53 \
        -command scan_imgs -takefocus {} -text 扫描图像 -cursor hand2 
    vTcl:DefineAlias "$top.tBu53" "scan_imgs_button" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu54 \
        -command orentation -takefocus {} -text 定向 -cursor hand2 
    vTcl:DefineAlias "$top.tBu54" "orentation_button" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu55 \
        -command match_points -takefocus {} -text 像点匹配 -cursor hand2 
    vTcl:DefineAlias "$top.tBu55" "match_button" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu56 \
        -takefocus {} -text 光束法平差 -cursor hand2 
    vTcl:DefineAlias "$top.tBu56" "bundle_adjustment_button" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu57 \
        -command display_3d_data -takefocus {} -text 三维数据显示 -cursor hand2 
    vTcl:DefineAlias "$top.tBu57" "display_3d_data_button" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr46 \
        -background $vTcl(actual_gui_bg) -height 653 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 127 
    vTcl:DefineAlias "$top.scr46" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    $top.scr46.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground blue \
        -selectforeground white \
        -width 10
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can49 \
        -in $top -x 0 -relx 0.217 -y 0 -width 0 -relwidth 0.778 -height 0 \
        -relheight 0.782 -anchor nw -bordermode ignore 
    place $top.scr50 \
        -in $top -x 0 -relx 0.123 -y 0 -rely 0.788 -width 0 -relwidth 0.876 \
        -height 0 -relheight 0.209 -anchor nw -bordermode ignore 
    place $top.tBu51 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.071 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu52 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.129 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu53 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.188 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu54 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.247 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu55 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.306 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu56 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.365 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu57 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.424 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr46 \
        -in $top -x 0 -relx 0.124 -y 0 -width 0 -relwidth 0.093 -height 0 \
        -relheight 0.787 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

