#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Jul 25, 2020 08:56:36 PM CST  platform: Windows NT

import sys
from IPG_GUI_support import SETTING_PARAMETER, SCAN_PARAMETER

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global selectedButton
    selectedButton = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global set_win, top_level, root
    set_win = gui
    top_level = top
    root = top


def code_scan_set_check_Button_click():
    print('scan_setting_win_support.code_scan_set_check_Button_click')
    print('变化之前的参数：', SETTING_PARAMETER.code_prefix_name,
          SETTING_PARAMETER.pt_proximity_factor,
          SETTING_PARAMETER.search_parameter,
          # SETTING_PARAMETER.match_pix_error,
          SETTING_PARAMETER.line_error,
          SETTING_PARAMETER.reject_factor,
          SETTING_PARAMETER.cross_error,
          SETTING_PARAMETER.affine_error)
    SETTING_PARAMETER.code_prefix_name = set_win.TEntry1.get()
    SETTING_PARAMETER.pt_proximity_factor = int(set_win.TEntry2.get())
    SETTING_PARAMETER.search_parameter = int(set_win.TEntry3.get())
    # SETTING_PARAMETER.match_pix_error = int(set_win.TEntry4.get())
    SETTING_PARAMETER.line_error = float(set_win.TEntry4.get())
    SETTING_PARAMETER.reject_factor = int(set_win.TEntry5.get())
    SETTING_PARAMETER.cross_error = float(set_win.TEntry6.get())
    SETTING_PARAMETER.affine_error = float(set_win.TEntry7.get())
    print('变化之后的参数：', SETTING_PARAMETER.code_prefix_name,
          SETTING_PARAMETER.pt_proximity_factor,
          SETTING_PARAMETER.search_parameter,
          # SETTING_PARAMETER.match_pix_error,
          SETTING_PARAMETER.line_error,
          SETTING_PARAMETER.reject_factor,
          SETTING_PARAMETER.cross_error,
          SETTING_PARAMETER.affine_error)

def code_scan_set_exit_Button_click():
    print('scan_setting_win_support.code_scan_set_exit_Button_click')
    destroy_window()

def single_pt_scan_set_button_click():
    print('scan_setting_win_support.single_pt_scan_set_button_click')
    print('变化之前的参数：', SCAN_PARAMETER.grid_threshold, SCAN_PARAMETER.pace, SCAN_PARAMETER.black_white_max_limit,
          SCAN_PARAMETER.deviation, SCAN_PARAMETER.pix_num_min_limit, SCAN_PARAMETER.pix_num_max_limit,
          SCAN_PARAMETER.width_min_limit, SCAN_PARAMETER.width_max_limit, SCAN_PARAMETER.height_min_limit,
          SCAN_PARAMETER.height_max_limit, SCAN_PARAMETER.shape, SCAN_PARAMETER.over_exposure, SCAN_PARAMETER.brightness)
    SCAN_PARAMETER.grid_threshold = int(set_win.grid_threshold_entry.get())
    SCAN_PARAMETER.pace = int(set_win.pace_entry.get())
    SCAN_PARAMETER.black_white_max_limit = float(set_win.black_white_entry.get())
    SCAN_PARAMETER.deviation = int(set_win.background_consistency_entry.get())
    SCAN_PARAMETER.pix_num_min_limit = int(set_win.min_total_pix_entry.get())
    SCAN_PARAMETER.pix_num_max_limit = int(set_win.max_total_pix_entry.get())
    SCAN_PARAMETER.width_min_limit = int(set_win.min_x_pix_entry.get())
    SCAN_PARAMETER.width_max_limit = int(set_win.max_x_pix_entry.get())
    SCAN_PARAMETER.height_min_limit = int(set_win.min_y_pix_entry.get())
    SCAN_PARAMETER.height_max_limit = int(set_win.max_y_pix_entry.get())
    SCAN_PARAMETER.shape = float(set_win.width_height_entry.get())
    SCAN_PARAMETER.over_exposure = float(set_win.over_exposure_ratio_entry.get() ) / 100
    SCAN_PARAMETER.brightness = int(set_win.gray_thrashold_entry.get())
    print('变化之后的参数：', SCAN_PARAMETER.grid_threshold, SCAN_PARAMETER.pace, SCAN_PARAMETER.black_white_max_limit,
          SCAN_PARAMETER.deviation, SCAN_PARAMETER.pix_num_min_limit, SCAN_PARAMETER.pix_num_max_limit,
          SCAN_PARAMETER.width_min_limit, SCAN_PARAMETER.width_max_limit, SCAN_PARAMETER.height_min_limit,
          SCAN_PARAMETER.height_max_limit, SCAN_PARAMETER.shape, SCAN_PARAMETER.over_exposure,
          SCAN_PARAMETER.brightness)

def single_pt_scan_set_exit_button_click():
    print('scan_setting_win_support.single_pt_scan_set_exit_button_click')
    destroy_window()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def main_start():
    import scan_setting_win
    scan_setting_win.vp_start_gui()




